### ISSUE TITLE
Add CLI Command for system-check

### ISSUE THREAD

**Issue by typoworx-de** [piwik/github-issues-mirror#8]
I vote for a CLI-Command to check if everything is running fine with PIWIK! I recently I accidently noticed that for some reason the Directory and MySQL-Permissions for Piwik where both screwed and PIWIK was NOT RUNNING for about one month and loosing trackings about that!!! Horrible!

I vote for some CLI-Command that is able to give some output for different important checks, that f.e. can be processed by MONIT or some other monitoring solutions to keep an eye on such horrible problems.

**Comment by sgiehl** [comment]
Could you please open the issue in the [piwik repo](https://github.com/piwik/piwik). This project isn't related with Piwik.
