### ISSUE TITLE
add link to github issue

### ISSUE THREAD

**Issue by Findus23** [piwik/github-issues-mirror#9]
Often when googling for an issue I come across the issue mirror. 
But when I want to interact with the issue, it's quite inconvinient having to copy the issue id and looking for the original issue.

It would be convenient if the "#[issueID]" in the h1 would directly link to the original issue.

**Comment by mattab** [comment]
@Findus23 Nice idea. PR welcome :+1:

**Comment by mattab** [comment]
fixed in https://github.com/piwik/github-issues-mirror/pull/10 @Findus23
